

version: '3.7'

services:
  backend:
    build:
      context: ./backend-api/simple-api-student-main
    ports:
      - "8080:8080"
    environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pwd
    networks:
      - app-network
    depends_on:
      - database


  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    networks:
      - app-network

  http:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:

